[package]
name = "sql_formatter"
version = "0.1.0"
authors = ["shyu61 <ohs6261@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
regex = "1.5.4"
structopt = "0.3.21"
